# Form implementation generated from reading ui file 'AddDiem.ui'
#
# Created by: PyQt6 UI code generator 6.5.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from functools import partial

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(349, 299)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btnCancel = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnCancel.setGeometry(QtCore.QRect(280, 220, 61, 24))
        self.btnCancel.setStyleSheet("background-color: rgb(170, 170, 127);")
        self.btnCancel.setObjectName("btnCancel")
        self.btnSave = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnSave.setGeometry(QtCore.QRect(210, 220, 61, 24))
        self.btnSave.setStyleSheet("background-color: rgb(0, 255, 127);")
        self.btnSave.setObjectName("btnSave")
        self.cbBoxMon_2 = QtWidgets.QComboBox(parent=self.centralwidget)
        self.cbBoxMon_2.setGeometry(QtCore.QRect(70, 10, 101, 22))
        self.cbBoxMon_2.setStyleSheet("font: 10pt \"Segoe UI\";")
        self.cbBoxMon_2.setObjectName("cbBoxMon_2")
        self.label_7 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(190, 10, 51, 16))
        self.label_7.setStyleSheet("font: 10pt \"Segoe UI\";")
        self.label_7.setObjectName("label_7")
        self.cbBoxHocKy = QtWidgets.QComboBox(parent=self.centralwidget)
        self.cbBoxHocKy.setGeometry(QtCore.QRect(240, 10, 101, 22))
        self.cbBoxHocKy.setStyleSheet("font: 10pt \"Segoe UI\";")
        self.cbBoxHocKy.setObjectName("cbBoxHocKy")
        self.label_6 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(10, 10, 61, 16))
        self.label_6.setStyleSheet("font: 10pt \"Segoe UI\";")
        self.label_6.setObjectName("label_6")
        self.label_8 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(10, 60, 81, 16))
        self.label_8.setStyleSheet("font: 10pt \"Segoe UI\";")
        self.label_8.setObjectName("label_8")
        self.lineEdit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(100, 60, 113, 22))
        self.lineEdit.setObjectName("lineEdit")
        self.viewSV = QtWidgets.QPushButton(parent=self.centralwidget)
        self.viewSV.setGeometry(QtCore.QRect(220, 60, 71, 21))
        self.viewSV.setStyleSheet("font: 7pt \"Segoe UI\";")
        self.viewSV.setObjectName("viewSV")
        self.groupBox = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 110, 191, 141))
        self.groupBox.setStyleSheet("background-color: rgb(170, 255, 255);\n"
"font: 10pt \"Segoe UI\";")
        self.groupBox.setObjectName("groupBox")
        self.label_9 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_9.setGeometry(QtCore.QRect(10, 30, 61, 16))
        self.label_9.setStyleSheet("font: 10pt \"Segoe UI\";")
        self.label_9.setObjectName("label_9")
        self.doubleQuaTrinh = QtWidgets.QDoubleSpinBox(parent=self.groupBox)
        self.doubleQuaTrinh.setGeometry(QtCore.QRect(80, 30, 62, 22))
        self.doubleQuaTrinh.setMaximum(10.0)
        self.doubleQuaTrinh.setObjectName("doubleQuaTrinh")
        self.doubleGiuaKy = QtWidgets.QDoubleSpinBox(parent=self.groupBox)
        self.doubleGiuaKy.setGeometry(QtCore.QRect(80, 60, 62, 22))
        self.doubleGiuaKy.setMaximum(10.0)
        self.doubleGiuaKy.setObjectName("doubleGiuaKy")
        self.label_10 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_10.setGeometry(QtCore.QRect(10, 60, 51, 16))
        self.label_10.setStyleSheet("font: 10pt \"Segoe UI\";")
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_11.setGeometry(QtCore.QRect(10, 90, 51, 21))
        self.label_11.setStyleSheet("font: 10pt \"Segoe UI\";")
        self.label_11.setObjectName("label_11")
        self.doubleCuoiKy = QtWidgets.QDoubleSpinBox(parent=self.groupBox)
        self.doubleCuoiKy.setGeometry(QtCore.QRect(80, 90, 62, 22))
        self.doubleCuoiKy.setMaximum(10.0)
        self.doubleCuoiKy.setObjectName("doubleCuoiKy")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 349, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.btnCancel.clicked.connect(partial(self.exit, MainWindow))

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def exit(self, MainWindow):
        MainWindow.hide()

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Thêm Bảng Điểm"))
        self.btnCancel.setText(_translate("MainWindow", "Hủy"))
        self.btnSave.setText(_translate("MainWindow", "Lưu"))
        self.label_7.setText(_translate("MainWindow", "Học Kỳ"))
        self.label_6.setText(_translate("MainWindow", "Môn Học"))
        self.label_8.setText(_translate("MainWindow", "Mã Sinh Viên"))
        self.viewSV.setText(_translate("MainWindow", "Xem thông tin"))
        self.groupBox.setTitle(_translate("MainWindow", "Nhập Điểm"))
        self.label_9.setText(_translate("MainWindow", "Quá trình"))
        self.label_10.setText(_translate("MainWindow", "Giữa kỳ"))
        self.label_11.setText(_translate("MainWindow", "Cuối kỳ"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
