# Form implementation generated from reading ui file 'AddLop.ui'
#
# Created by: PyQt6 UI code generator 6.5.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from functools import partial
from database import *

myDB = MY_DB()

class Ui_MainWindow(object):
    global myDB
    def setupUi(self, MainWindow):
        myDB.connect()
        self.MainWindow = MainWindow

        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(451, 191)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_4 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(10, 120, 91, 16))
        self.label_4.setStyleSheet("font: 10pt \"Segoe UI\";")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(240, 40, 49, 16))
        self.label_5.setStyleSheet("font: 10pt \"Segoe UI\";")
        self.label_5.setObjectName("label_5")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 80, 81, 16))
        self.label_3.setStyleSheet("font: 10pt \"Segoe UI\";")
        self.label_3.setObjectName("label_3")
        self.IDLop = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.IDLop.setGeometry(QtCore.QRect(110, 40, 101, 22))
        self.IDLop.setStyleSheet("font: 10pt \"Segoe UI\";")
        self.IDLop.setReadOnly(False)
        self.IDLop.setObjectName("IDLop")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 40, 49, 16))
        self.label_2.setStyleSheet("font: 10pt \"Segoe UI\";")
        self.label_2.setObjectName("label_2")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 10, 171, 16))
        self.label.setStyleSheet("font: 700 12pt \"Segoe UI\";")
        self.label.setObjectName("label")
        self.NameLop = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.NameLop.setGeometry(QtCore.QRect(310, 40, 131, 22))
        self.NameLop.setStyleSheet("font: 10pt \"Segoe UI\";")
        self.NameLop.setReadOnly(False)
        self.NameLop.setObjectName("NameLop")
        self.btnSave = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnSave.setGeometry(QtCore.QRect(300, 120, 61, 24))
        self.btnSave.setStyleSheet("background-color: rgb(0, 255, 127);")
        self.btnSave.setObjectName("btnSave")
        self.btnCancel = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnCancel.setGeometry(QtCore.QRect(380, 120, 61, 24))
        self.btnCancel.setStyleSheet("background-color: rgb(170, 170, 127);")
        self.btnCancel.setObjectName("btnCancel")
        self.cbBoxNghanh = QtWidgets.QComboBox(parent=self.centralwidget)
        self.cbBoxNghanh.setGeometry(QtCore.QRect(110, 80, 101, 22))
        self.cbBoxNghanh.setObjectName("cbBoxNghanh")
        self.cbBoxNienKhoa = QtWidgets.QComboBox(parent=self.centralwidget)
        self.cbBoxNienKhoa.setGeometry(QtCore.QRect(110, 120, 131, 22))
        self.cbBoxNienKhoa.setObjectName("cbBoxNienKhoa")
        self.err = QtWidgets.QLabel(parent=self.centralwidget)
        self.err.setGeometry(QtCore.QRect(280, 90, 161, 20))
        self.err.setStyleSheet("color: rgb(170, 0, 0);\n"
"font: 10pt \"Segoe UI\";")
        self.err.setText("")
        self.err.setObjectName("err")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 451, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.btnCancel.clicked.connect(self.close)

        self.nghanhTable = myDB.select_all_nghanh()
        self.cbBoxNghanh.clear()  # Xóa danh sách cũ trong combobox trước khi thêm mới
        for row_data in self.nghanhTable:
                ma_nghanh = row_data[0] 
                #ten_khoa = row_data[1]
                self.cbBoxNghanh.addItem(str(ma_nghanh))
                # self.cbBoxKhoa.addItem(str(ma_khoa + "-" + ten_khoa))

        self.nienkhoaTable = myDB.select_all_nienkhoa()
        self.cbBoxNienKhoa.clear()  # Xóa danh sách cũ trong combobox trước khi thêm mới
        for row_data in self.nienkhoaTable:
                ma_nienkhoa = row_data[0] 
                ten_nienkhoa = row_data[1]
                self.cbBoxNienKhoa.addItem(str(ma_nienkhoa) + " - " + str(ten_nienkhoa))

        self.btnSave.clicked.connect(partial(self.on_btnSave_clicked, MainWindow))

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def new_window(self):
        self.IDLop.setText("")
        self.NameLop.setText("")
        self.cbBoxNghanh.setCurrentIndex(0)
        self.cbBoxNienKhoa.setCurrentIndex(0)
        self.err.setText("")

    def close(self):
        self.MainWindow.close() 

    def on_btnSave_clicked(self, MainWindow):
        malop = self.IDLop.text()
        tenlop = self.NameLop.text()
        manghanh = self.cbBoxNghanh.currentText()
        nienkhoa = self.cbBoxNienKhoa.currentText().split(" ")
        manNienkhoa = nienkhoa[0]

        lop = myDB.select_lop_by_id(malop).fetchone()
        if lop != None:
            self.err.setText("Mã lớp đã tồn tại !!")
            return

        if malop == "" or tenlop == "":
            self.err.setText("Không bỏ trống thông tin !!")
            return
        myDB.insert_lop(malop, manghanh, manNienkhoa, tenlop)
        self.MainWindow.close() 

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Thêm Lớp"))
        self.label_4.setText(_translate("MainWindow", "Mã Niên Khóa"))
        self.label_5.setText(_translate("MainWindow", "Tên Lớp"))
        self.label_3.setText(_translate("MainWindow", "Mã Nghành"))
        self.label_2.setText(_translate("MainWindow", "Mã Lớp"))
        self.label.setText(_translate("MainWindow", "THÔNG TIN LỚP"))
        self.btnSave.setText(_translate("MainWindow", "Lưu"))
        self.btnCancel.setText(_translate("MainWindow", "Hủy"))

def closeWindow():
    global myDB
    myDB.disconnect()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    app.setQuitOnLastWindowClosed(False)
    app.lastWindowClosed.connect(closeWindow)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
