# Form implementation generated from reading ui file 'AddSV.ui'
#
# Created by: PyQt6 UI code generator 6.5.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtCore import QDate
from functools import partial
from database import *

myDB = MY_DB()

class Ui_MainWindow(object):
    global myDB
    def setupUi(self, MainWindow):
        myDB.connect()
        self.MainWindow = MainWindow

        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(484, 309)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.cbBoxSex = QtWidgets.QComboBox(parent=self.centralwidget)
        self.cbBoxSex.setGeometry(QtCore.QRect(110, 120, 69, 22))
        self.cbBoxSex.setObjectName("cbBoxSex")
        self.cbBoxSex.addItem("")
        self.cbBoxSex.addItem("")
        self.cbBoxSex.addItem("")
        self.NameSV = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.NameSV.setGeometry(QtCore.QRect(110, 80, 131, 22))
        self.NameSV.setStyleSheet("font: 10pt \"Segoe UI\";")
        self.NameSV.setReadOnly(False)
        self.NameSV.setObjectName("NameSV")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 40, 49, 16))
        self.label_2.setStyleSheet("font: 10pt \"Segoe UI\";")
        self.label_2.setObjectName("label_2")
        self.label_6 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(10, 120, 51, 16))
        self.label_6.setStyleSheet("font: 10pt \"Segoe UI\";")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(270, 120, 51, 16))
        self.label_7.setStyleSheet("font: 10pt \"Segoe UI\";")
        self.label_7.setObjectName("label_7")
        self.detailDanToc = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.detailDanToc.setGeometry(QtCore.QRect(340, 120, 131, 22))
        self.detailDanToc.setStyleSheet("font: 10pt \"Segoe UI\";")
        self.detailDanToc.setReadOnly(False)
        self.detailDanToc.setObjectName("detailDanToc")
        self.detailSDT = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.detailSDT.setGeometry(QtCore.QRect(340, 160, 131, 22))
        self.detailSDT.setStyleSheet("font: 10pt \"Segoe UI\";")
        self.detailSDT.setReadOnly(False)
        self.detailSDT.setObjectName("detailSDT")
        self.label_8 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(10, 160, 51, 16))
        self.label_8.setStyleSheet("font: 10pt \"Segoe UI\";")
        self.label_8.setObjectName("label_8")
        self.label_5 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(270, 80, 71, 21))
        self.label_5.setStyleSheet("font: 10pt \"Segoe UI\";")
        self.label_5.setObjectName("label_5")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 10, 181, 16))
        self.label.setStyleSheet("font: 700 12pt \"Segoe UI\";")
        self.label.setObjectName("label")
        self.label_4 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(10, 80, 51, 16))
        self.label_4.setStyleSheet("font: 10pt \"Segoe UI\";")
        self.label_4.setObjectName("label_4")
        self.dateOfB = QtWidgets.QDateEdit(parent=self.centralwidget)
        self.dateOfB.setGeometry(QtCore.QRect(340, 80, 131, 22))
        self.dateOfB.setReadOnly(False)
        self.dateOfB.setObjectName("dateOfB")
        self.label_9 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(270, 160, 51, 16))
        self.label_9.setStyleSheet("font: 10pt \"Segoe UI\";")
        self.label_9.setObjectName("label_9")
        self.plainTextEditDiaChi = QtWidgets.QPlainTextEdit(parent=self.centralwidget)
        self.plainTextEditDiaChi.setGeometry(QtCore.QRect(110, 160, 131, 101))
        self.plainTextEditDiaChi.setReadOnly(False)
        self.plainTextEditDiaChi.setObjectName("plainTextEditDiaChi")
        self.cbBoxLop = QtWidgets.QComboBox(parent=self.centralwidget)
        self.cbBoxLop.setGeometry(QtCore.QRect(110, 40, 111, 22))
        self.cbBoxLop.setObjectName("cbBoxLop")
        self.btnSave = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnSave.setGeometry(QtCore.QRect(270, 230, 61, 24))
        self.btnSave.setStyleSheet("background-color: rgb(0, 255, 127);")
        self.btnSave.setObjectName("btnSave")
        self.errAddSV = QtWidgets.QLabel(parent=self.centralwidget)
        self.errAddSV.setGeometry(QtCore.QRect(270, 190, 151, 31))
        self.errAddSV.setStyleSheet("color: rgb(170, 0, 0);\n"
"font: 10pt \"Segoe UI\";")
        self.errAddSV.setText("")
        self.errAddSV.setObjectName("errAddSV")
        self.btnCancel = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnCancel.setGeometry(QtCore.QRect(360, 230, 61, 24))
        self.btnCancel.setStyleSheet("background-color: rgb(170, 170, 127);")
        self.btnCancel.setObjectName("btnCancel")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 484, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.btnCancel.clicked.connect(self.close)

        self.lopTable = myDB.select_all_lop()
        self.cbBoxLop.clear()  # Xóa danh sách cũ trong combobox trước khi thêm mới
        for row_data in self.lopTable:
                ma_lop = row_data[0] 
                self.cbBoxLop.addItem(ma_lop)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.btnSave.clicked.connect(partial(self.on_btnSave_clicked, MainWindow))

    def on_btnSave_clicked(self, MainWindow):
        current_IDLop = self.cbBoxLop.currentText()
        current_name = self.NameSV.text()

        date_of_birth = self.dateOfB.date()
        current_dob = date_of_birth.toString("yyyy-MM-dd")

        current_gender = 1
        if self.cbBoxSex.currentText() == "Nam":
            current_gender = 0
        elif self.cbBoxSex.currentText() == "Nữ":
            current_gender = 1
        else:
            current_gender = 2

        current_dantoc = self.detailDanToc.text()
        current_diachi = self.plainTextEditDiaChi.toPlainText()
        current_sdt = self.detailSDT.text()

        if current_name == "" or current_dantoc == "" or current_diachi == "" or current_sdt == "":
            self.errAddSV.setText("Không bỏ trống thông tin !!")
            return

        myDB.insert_sinhvien(current_IDLop, current_name, current_dob, current_gender, current_dantoc, current_diachi, current_sdt)
        self.MainWindow.close() 

    def new_window(self):
        self.cbBoxLop.setCurrentIndex(0)
        self.NameSV.setText("")
        self.cbBoxSex.setCurrentIndex(0)
        self.plainTextEditDiaChi.setPlainText("")
        # Lấy ngày hiện tại
        ngay_hien_tai = QDate.currentDate()
        self.dateOfB.setDate(ngay_hien_tai)
        self.detailDanToc.setText("")
        self.detailSDT.setText("")
        self.errAddSV.setText("")

    def close(self):
        self.MainWindow.close() 

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Thêm Sinh Viến"))
        self.cbBoxSex.setItemText(0, _translate("MainWindow", "Nam"))
        self.cbBoxSex.setItemText(1, _translate("MainWindow", "Nữ"))
        self.cbBoxSex.setItemText(2, _translate("MainWindow", "Khác"))
        self.label_2.setText(_translate("MainWindow", "Mã Lớp"))
        self.label_6.setText(_translate("MainWindow", "Giới Tính"))
        self.label_7.setText(_translate("MainWindow", "Dân Tộc"))
        self.label_8.setText(_translate("MainWindow", "Địa Chỉ"))
        self.label_5.setText(_translate("MainWindow", "Ngày Sinh"))
        self.label.setText(_translate("MainWindow", "THÔNG TIN SINH VIÊN"))
        self.label_4.setText(_translate("MainWindow", "Họ Tên"))
        self.dateOfB.setDisplayFormat(_translate("MainWindow", "d/M/yyyy"))
        self.label_9.setText(_translate("MainWindow", "Liên Hệ"))
        self.btnSave.setText(_translate("MainWindow", "Lưu"))
        self.btnCancel.setText(_translate("MainWindow", "Hủy"))

def closeWindow():
    global myDB
    myDB.disconnect()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    app.setQuitOnLastWindowClosed(False)
    app.lastWindowClosed.connect(closeWindow)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
