# Form implementation generated from reading ui file 'DetailDiem.ui'
#
# Created by: PyQt6 UI code generator 6.5.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(349, 299)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.groupBox = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 110, 191, 141))
        self.groupBox.setStyleSheet("background-color: rgb(170, 255, 255);\n"
"font: 10pt \"Segoe UI\";")
        self.groupBox.setObjectName("groupBox")
        self.label_12 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_12.setGeometry(QtCore.QRect(10, 30, 61, 16))
        self.label_12.setStyleSheet("font: 10pt \"Segoe UI\";")
        self.label_12.setObjectName("label_12")
        self.doubleQuaTrinh_2 = QtWidgets.QDoubleSpinBox(parent=self.groupBox)
        self.doubleQuaTrinh_2.setGeometry(QtCore.QRect(80, 30, 62, 22))
        self.doubleQuaTrinh_2.setReadOnly(False)
        self.doubleQuaTrinh_2.setMaximum(10.0)
        self.doubleQuaTrinh_2.setObjectName("doubleQuaTrinh_2")
        self.doubleGiuaKy_2 = QtWidgets.QDoubleSpinBox(parent=self.groupBox)
        self.doubleGiuaKy_2.setGeometry(QtCore.QRect(80, 60, 62, 22))
        self.doubleGiuaKy_2.setMaximum(10.0)
        self.doubleGiuaKy_2.setObjectName("doubleGiuaKy_2")
        self.label_13 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_13.setGeometry(QtCore.QRect(10, 60, 51, 16))
        self.label_13.setStyleSheet("font: 10pt \"Segoe UI\";")
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_14.setGeometry(QtCore.QRect(10, 90, 51, 21))
        self.label_14.setStyleSheet("font: 10pt \"Segoe UI\";")
        self.label_14.setObjectName("label_14")
        self.doubleCuoiKy_2 = QtWidgets.QDoubleSpinBox(parent=self.groupBox)
        self.doubleCuoiKy_2.setGeometry(QtCore.QRect(80, 90, 62, 22))
        self.doubleCuoiKy_2.setMaximum(10.0)
        self.doubleCuoiKy_2.setObjectName("doubleCuoiKy_2")
        self.label_6 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(10, 10, 61, 16))
        self.label_6.setStyleSheet("font: 10pt \"Segoe UI\";")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(190, 10, 51, 16))
        self.label_7.setStyleSheet("font: 10pt \"Segoe UI\";")
        self.label_7.setObjectName("label_7")
        self.maSV = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.maSV.setGeometry(QtCore.QRect(100, 60, 113, 22))
        self.maSV.setReadOnly(True)
        self.maSV.setObjectName("maSV")
        self.label_8 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(10, 60, 81, 16))
        self.label_8.setStyleSheet("font: 10pt \"Segoe UI\";")
        self.label_8.setObjectName("label_8")
        self.btnClose = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnClose.setGeometry(QtCore.QRect(280, 220, 61, 24))
        self.btnClose.setStyleSheet("")
        self.btnClose.setObjectName("btnClose")
        self.btnEdit = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnEdit.setGeometry(QtCore.QRect(210, 220, 61, 24))
        self.btnEdit.setStyleSheet("background-color: rgb(255, 170, 0);")
        self.btnEdit.setObjectName("btnEdit")
        self.maMH = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.maMH.setGeometry(QtCore.QRect(70, 10, 113, 22))
        self.maMH.setReadOnly(True)
        self.maMH.setObjectName("maMH")
        self.hocky = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.hocky.setGeometry(QtCore.QRect(240, 10, 81, 22))
        self.hocky.setReadOnly(True)
        self.hocky.setObjectName("hocky")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 349, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Chi Tiết Bảng Điểm"))
        self.groupBox.setTitle(_translate("MainWindow", "Điểm "))
        self.label_12.setText(_translate("MainWindow", "Quá trình"))
        self.label_13.setText(_translate("MainWindow", "Giữa kỳ"))
        self.label_14.setText(_translate("MainWindow", "Cuối kỳ"))
        self.label_6.setText(_translate("MainWindow", "Môn Học"))
        self.label_7.setText(_translate("MainWindow", "Học Kỳ"))
        self.label_8.setText(_translate("MainWindow", "Mã Sinh Viên"))
        self.btnClose.setText(_translate("MainWindow", "Đóng"))
        self.btnEdit.setText(_translate("MainWindow", "Sửa"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
