# Form implementation generated from reading ui file 'DetailLop.ui'
#
# Created by: PyQt6 UI code generator 6.5.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.

from PyQt6 import QtCore, QtGui, QtWidgets
from functools import partial
from database import *

myDB = MY_DB()


class Ui_MainWindow(object):
    selectedMaLop = None
    global myDB
    def setupUi(self, MainWindow):
        myDB.connect()
        self.MainWindow = MainWindow
        
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(453, 190)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 10, 171, 16))
        self.label.setStyleSheet("font: 700 12pt \"Segoe UI\";")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 40, 49, 16))
        self.label_2.setStyleSheet("font: 10pt \"Segoe UI\";")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, 80, 81, 21))
        self.label_3.setStyleSheet("font: 10pt \"Segoe UI\";")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(10, 120, 91, 16))
        self.label_4.setStyleSheet("font: 10pt \"Segoe UI\";")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(250, 40, 49, 16))
        self.label_5.setStyleSheet("font: 10pt \"Segoe UI\";")
        self.label_5.setObjectName("label_5")
        self.detailIDLop = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.detailIDLop.setGeometry(QtCore.QRect(110, 40, 101, 22))
        self.detailIDLop.setStyleSheet("font: 10pt \"Segoe UI\";")
        self.detailIDLop.setReadOnly(True)
        self.detailIDLop.setObjectName("detailIDLop")
        self.detailNameLop = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.detailNameLop.setGeometry(QtCore.QRect(310, 40, 131, 22))
        self.detailNameLop.setStyleSheet("font: 10pt \"Segoe UI\";")
        self.detailNameLop.setReadOnly(False)
        self.detailNameLop.setObjectName("detailNameLop")
        self.btnEdit = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnEdit.setGeometry(QtCore.QRect(290, 120, 61, 24))
        self.btnEdit.setStyleSheet("background-color: rgb(255, 170, 0);")
        self.btnEdit.setObjectName("btnEdit")
        self.btnClose = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnClose.setGeometry(QtCore.QRect(380, 120, 61, 24))
        self.btnClose.setStyleSheet("background-color: rgb(171, 171, 171);")
        self.btnClose.setObjectName("btnClose")
        self.detailIDNghanh = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.detailIDNghanh.setGeometry(QtCore.QRect(110, 80, 101, 22))
        self.detailIDNghanh.setStyleSheet("font: 10pt \"Segoe UI\";")
        self.detailIDNghanh.setReadOnly(True)
        self.detailIDNghanh.setObjectName("detailIDNghanh")
        self.detailIDNienKhoa = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.detailIDNienKhoa.setGeometry(QtCore.QRect(110, 120, 101, 22))
        self.detailIDNienKhoa.setStyleSheet("font: 10pt \"Segoe UI\";")
        self.detailIDNienKhoa.setReadOnly(True)
        self.detailIDNienKhoa.setObjectName("detailIDNienKhoa")
        self.err = QtWidgets.QLabel(parent=self.centralwidget)
        self.err.setGeometry(QtCore.QRect(280, 90, 161, 20))
        self.err.setStyleSheet("color: rgb(170, 0, 0);\n"
"font: 10pt \"Segoe UI\";")
        self.err.setText("")
        self.err.setObjectName("err")
        self.lock1 = QtWidgets.QLabel(parent=self.centralwidget)
        self.lock1.setGeometry(QtCore.QRect(220, 40, 21, 21))
        self.lock1.setText("")
        self.lock1.setPixmap(QtGui.QPixmap("images/lock.png"))
        self.lock1.setScaledContents(True)
        self.lock1.setWordWrap(False)
        self.lock1.setObjectName("lock1")
        self.lock2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.lock2.setGeometry(QtCore.QRect(220, 80, 21, 21))
        self.lock2.setText("")
        self.lock2.setPixmap(QtGui.QPixmap("images/lock.png"))
        self.lock2.setScaledContents(True)
        self.lock2.setWordWrap(False)
        self.lock2.setObjectName("lock2")
        self.lock2_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.lock2_2.setGeometry(QtCore.QRect(220, 120, 21, 21))
        self.lock2_2.setText("")
        self.lock2_2.setPixmap(QtGui.QPixmap("images/lock.png"))
        self.lock2_2.setScaledContents(True)
        self.lock2_2.setWordWrap(False)
        self.lock2_2.setObjectName("lock2_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 453, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        if self.selectedMaLop != None:
            # Lấy thông tin lớp từ CSDL dựa trên selectedMaLop
            lop = myDB.select_lop_by_id(self.selectedMaLop).fetchone()

            # Hiển thị thông tin lớp trong giao diện DetailLop
            self.detailIDLop.setText(lop[0])
            self.detailIDNghanh.setText(lop[1])
            self.detailIDNienKhoa.setText(myDB.get_ten_nien_khoa(lop[2]))
            self.detailNameLop.setText(lop[3])
        
        self.btnEdit.clicked.connect(partial(self.update_data, MainWindow))
        self.btnClose.clicked.connect(self.close)

    def set_selected_maLop(self, maLop):
        self.selectedMaLop = maLop

    def update_data(self, MainWindow):
        # from QuanLyLop import Ui_MainWindow as Ui_MainWindow
        current_id = self.detailIDLop.text()
        current_name = self.detailNameLop.text().strip()
        current_lop =  myDB.select_lop_by_id(current_id).fetchone()

        if current_name == "":
            self.err.setText("Không bỏ trống thông tin !!")
            return
        
        if current_name != current_lop[3]:
            myDB.update_lop(current_name, current_id)
        self.MainWindow.close() 
        
    def close(self):
        self.MainWindow.close() 
        
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Chi Tiết Lớp"))
        self.label.setText(_translate("MainWindow", "THÔNG TIN LỚP"))
        self.label_2.setText(_translate("MainWindow", "Mã Lớp"))
        self.label_3.setText(_translate("MainWindow", "Mã Nghành"))
        self.label_4.setText(_translate("MainWindow", "Mã Niên Khóa"))
        self.label_5.setText(_translate("MainWindow", "Tên Lớp"))
        self.btnEdit.setText(_translate("MainWindow", "Sửa"))
        self.btnClose.setText(_translate("MainWindow", "Đóng"))

def closeWindow():
    global myDB
    myDB.disconnect()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    app.setQuitOnLastWindowClosed(False)
    app.lastWindowClosed.connect(closeWindow)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
