# Form implementation generated from reading ui file 'QuanLyKhoa.ui'
#
# Created by: PyQt6 UI code generator 6.5.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from functools import partial
from database import *

myDB = MY_DB()

class Ui_QuanLyKhoa(object):
    global myDB
    def setupUi(self, QuanLyKhoa):
        myDB.connect()

        QuanLyKhoa.setObjectName("QuanLyKhoa")
        QuanLyKhoa.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(parent=QuanLyKhoa)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 50, 131, 16))
        self.label.setStyleSheet("font: 700 12pt \"Segoe UI\";")
        self.label.setObjectName("label")
        self.groupBox = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(430, 270, 361, 181))
        self.groupBox.setStyleSheet("background-color: rgb(112, 200, 255);\n"
"font: 10pt \"Segoe UI\";")
        self.groupBox.setObjectName("groupBox")
        self.label_2 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(10, 50, 71, 16))
        self.label_2.setStyleSheet("font: 10pt \"Segoe UI\";")
        self.label_2.setObjectName("label_2")
        self.detailIDKhoa = QtWidgets.QLineEdit(parent=self.groupBox)
        self.detailIDKhoa.setGeometry(QtCore.QRect(80, 50, 113, 22))
        self.detailIDKhoa.setStyleSheet("font: 10pt \"Segoe UI\";")
        self.detailIDKhoa.setReadOnly(True)
        self.detailIDKhoa.setObjectName("detailIDKhoa")
        self.label_3 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(10, 110, 71, 16))
        self.label_3.setStyleSheet("font: 10pt \"Segoe UI\";")
        self.label_3.setObjectName("label_3")
        self.detailNameKhoa = QtWidgets.QLineEdit(parent=self.groupBox)
        self.detailNameKhoa.setGeometry(QtCore.QRect(80, 110, 161, 22))
        self.detailNameKhoa.setStyleSheet("font: 10pt \"Segoe UI\";")
        self.detailNameKhoa.setReadOnly(True)
        self.detailNameKhoa.setObjectName("detailNameKhoa")
        self.btnEdit = QtWidgets.QPushButton(parent=self.groupBox)
        self.btnEdit.setGeometry(QtCore.QRect(200, 140, 61, 24))
        self.btnEdit.setStyleSheet("background-color: rgb(255, 170, 0);")
        self.btnEdit.setObjectName("btnEdit")
        self.btnDelete = QtWidgets.QPushButton(parent=self.groupBox)
        self.btnDelete.setGeometry(QtCore.QRect(280, 140, 61, 24))
        self.btnDelete.setStyleSheet("background-color: rgb(170, 0, 0);\n"
"color: rgb(255, 255, 255);")
        self.btnDelete.setObjectName("btnDelete")
        self.groupBox_2 = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(430, 80, 361, 181))
        self.groupBox_2.setStyleSheet("background-color: rgb(255, 240, 166);\n"
"font: 10pt \"Segoe UI\";")
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_4 = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label_4.setGeometry(QtCore.QRect(10, 50, 71, 16))
        self.label_4.setStyleSheet("font: 10pt \"Segoe UI\";")
        self.label_4.setObjectName("label_4")
        self.IDKhoa = QtWidgets.QLineEdit(parent=self.groupBox_2)
        self.IDKhoa.setGeometry(QtCore.QRect(80, 50, 113, 22))
        self.IDKhoa.setStyleSheet("font: 10pt \"Segoe UI\";")
        self.IDKhoa.setText("")
        self.IDKhoa.setReadOnly(False)
        self.IDKhoa.setObjectName("IDKhoa")
        self.label_5 = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label_5.setGeometry(QtCore.QRect(10, 110, 71, 16))
        self.label_5.setStyleSheet("font: 10pt \"Segoe UI\";")
        self.label_5.setObjectName("label_5")
        self.NameKhoa = QtWidgets.QLineEdit(parent=self.groupBox_2)
        self.NameKhoa.setGeometry(QtCore.QRect(80, 110, 161, 22))
        self.NameKhoa.setStyleSheet("font: 10pt \"Segoe UI\";")
        self.NameKhoa.setReadOnly(False)
        self.NameKhoa.setObjectName("NameKhoa")
        self.btnSave = QtWidgets.QPushButton(parent=self.groupBox_2)
        self.btnSave.setGeometry(QtCore.QRect(200, 140, 61, 24))
        self.btnSave.setStyleSheet("background-color: rgb(0, 255, 127);")
        self.btnSave.setObjectName("btnSave")
        self.btnCancel = QtWidgets.QPushButton(parent=self.groupBox_2)
        self.btnCancel.setGeometry(QtCore.QRect(280, 140, 61, 24))
        self.btnCancel.setStyleSheet("background-color: rgb(170, 170, 127);")
        self.btnCancel.setObjectName("btnCancel")
        self.label_6 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(430, 50, 131, 21))
        self.label_6.setStyleSheet("font: 700 12pt \"Segoe UI\";")
        self.label_6.setObjectName("label_6")
        self.btnSort = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnSort.setGeometry(QtCore.QRect(340, 40, 81, 31))
        self.btnSort.setStyleSheet("background-color: rgb(255, 182, 153);\n"
"font: 10pt \"Segoe UI\";")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("images/ic/icsort.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btnSort.setIcon(icon)
        self.btnSort.setIconSize(QtCore.QSize(20, 20))
        self.btnSort.setObjectName("btnSort")
        self.btnReload = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnReload.setGeometry(QtCore.QRect(430, 460, 91, 31))
        self.btnReload.setStyleSheet("background-color: rgb(16, 16, 255);\n"
"font: 10pt \"Segoe UI\";\n"
"color: rgb(255, 255, 255);")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("images/ic/icreload.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btnReload.setIcon(icon1)
        self.btnReload.setIconSize(QtCore.QSize(20, 20))
        self.btnReload.setObjectName("btnReload")
        self.btnHome = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnHome.setGeometry(QtCore.QRect(10, 10, 71, 31))
        self.btnHome.setStyleSheet("font: 10pt \"Segoe UI\";\n"
"background-color: rgb(255, 255, 127);")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("images/ic/icHome.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btnHome.setIcon(icon2)
        self.btnHome.setIconSize(QtCore.QSize(20, 20))
        self.btnHome.setObjectName("btnHome")
        self.tableKhoa = QtWidgets.QTableWidget(parent=self.centralwidget)
        self.tableKhoa.setGeometry(QtCore.QRect(10, 80, 411, 471))
        self.tableKhoa.setAutoScrollMargin(16)
        self.tableKhoa.setRowCount(5)
        self.tableKhoa.setColumnCount(2)
        self.tableKhoa.setObjectName("tableKhoa")
        item = QtWidgets.QTableWidgetItem()
        self.tableKhoa.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableKhoa.setHorizontalHeaderItem(1, item)
        QuanLyKhoa.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=QuanLyKhoa)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 22))
        self.menubar.setObjectName("menubar")
        QuanLyKhoa.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=QuanLyKhoa)
        self.statusbar.setObjectName("statusbar")
        QuanLyKhoa.setStatusBar(self.statusbar)
        self.btnHome.clicked.connect(partial(self.goHome, QuanLyKhoa))

        self.retranslateUi(QuanLyKhoa)
        QtCore.QMetaObject.connectSlotsByName(QuanLyKhoa)

        self.khoaTable = myDB.select_all_khoa()
        self.tableKhoa.setRowCount(0)
        for row_num, row_data in enumerate(self.khoaTable):
                self.tableKhoa.insertRow(row_num)
                for col_num, col_data in enumerate(row_data):
                     self.tableKhoa.setItem(row_num, col_num, QtWidgets.QTableWidgetItem(str(col_data)))
                
        self.tableKhoa.cellClicked.connect(self.on_tableKhoa_cellClicked)
        self.btnEdit.clicked.connect(self.enable_edit_mode)
        self.btnReload.clicked.connect(self.reload_data)

        self.btnSave.clicked.connect(self.on_btnSave_clicked)
        self.btnCancel.clicked.connect(self.cancel)

        self.btnDelete.clicked.connect(self.delete)

        self.btnSort.clicked.connect(self.sort_table_alphabetically)

    def goHome(self, MainWindow):
        from MainWindow import Ui_MainWindow as Ui_MainWindow
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_MainWindow()
        self.ui.setupUi(self.window)
        MainWindow.close()
        self.window.show()
    
#-----------------------------INSERT--------------------------------------------
    # def get_khoa_info(self):
    #     makhoa = self.IDKhoa.text()
    #     tenkhoa = self.NameKhoa.text()
    #     return makhoa, tenkhoa

    def on_btnSave_clicked(self):
        makhoa = self.IDKhoa.text().strip()
        tenkhoa = self.NameKhoa.text().strip()

        khoa = myDB.select_khoa_by_id(makhoa).fetchall()

        if makhoa == "" or tenkhoa == "" or khoa:
             return self.load_data()
        
        # Thêm khoa vào CSDL
        myDB.insert_khoa(makhoa, tenkhoa)
        self.cancel()
        # # Thông báo thành công
        # QtWidgets.QMessageBox.information(self, "Thông báo", f"Thêm khoa {makhoa} thành công.")
        self.load_data()

    def cancel(self):
        self.IDKhoa.setText("")
        self.NameKhoa.setText("")

#---------------------------------- UPDATE--------------------------------------
    def on_tableKhoa_cellClicked(self, row, column):
        # Lấy mã khoa từ dòng được click
        makhoa = self.tableKhoa.item(row, 0).text()

        # Lấy thông tin khoa từ CSDL
        khoa = myDB.select_khoa_by_id(makhoa).fetchone()

        # Hiển thị thông tin khoa trong groupBox
        self.detailIDKhoa.setText(khoa[0])
        self.detailNameKhoa.setText(khoa[1])

    def enable_edit_mode(self):
        current_id = self.detailIDKhoa.text()
        current_name = self.detailNameKhoa.text()
        if(current_id == "" and current_name == ""):
             return self.load_data()
        else: 
             #self.detailIDKhoa.setReadOnly(False)
             self.detailNameKhoa.setReadOnly(False)

    def current_selected_khoa(self):
        selected_rows = self.tableKhoa.selectedIndexes()
        if selected_rows:
                row = selected_rows[0].row()
                ma_khoa = self.tableKhoa.item(row, 0).text()
                ten_khoa = self.tableKhoa.item(row, 1).text()
                self.detailIDKhoa.setText(ma_khoa)
                self.detailNameKhoa.setText(ten_khoa)
                return (ma_khoa, ten_khoa)

    def reload_data(self):
        current_id = self.detailIDKhoa.text()
        current_name = self.detailNameKhoa.text()
        if(current_id == "" and current_name == ""):
             return self.load_data()
        if not self.detailNameKhoa.isReadOnly() and \
                (current_id, current_name) != self.current_selected_khoa():
                myDB.update_khoa(current_name, current_id)
                #self.detailIDKhoa.setReadOnly(True)
                self.detailNameKhoa.setReadOnly(True)
        self.detailIDKhoa.setText("")
        self.detailNameKhoa.setText("")
        self.load_data()
#-----------------------------------DELETE----------------------------------------------------
    def delete(self):
        current_id = self.detailIDKhoa.text()
        current_name = self.detailNameKhoa.text()
        if(current_id == "" and current_name == ""):
             return self.load_data()
        else:
             myDB.delete_khoa(current_id)
             self.detailIDKhoa.setText("")
             self.detailNameKhoa.setText("")
             self.load_data()
#----------------------------------SORT--------------------------------------------------------
    def sort_table_alphabetically(self):
        # Lấy số cột trong bảng
        column_count = self.tableKhoa.columnCount()
        # Lấy số hàng trong bảng
        row_count = self.tableKhoa.rowCount()
        # Tạo một danh sách các dòng trong bảng, mỗi dòng là một list các giá trị trong ô
        rows = [[self.tableKhoa.item(row, col).text() for col in range(column_count)] for row in range(row_count)]
        # Sắp xếp các dòng theo thứ tự tăng dần của cột tên khoa (cột thứ hai)
        sorted_rows = sorted(rows, key=lambda row: row[1])
        # Xóa tất cả các hàng cũ trong bảng
        self.tableKhoa.setRowCount(0)
        # Thêm các hàng đã sắp xếp vào bảng
        for row in sorted_rows:
                self.tableKhoa.insertRow(self.tableKhoa.rowCount())
                for col, value in enumerate(row):
                        item = QtWidgets.QTableWidgetItem(value)
                        self.tableKhoa.setItem(self.tableKhoa.rowCount() - 1, col, item)

    def load_data(self):
        self.khoaTable = myDB.select_all_khoa()
        self.tableKhoa.setRowCount(0)
        for row_num, row_data in enumerate(self.khoaTable):
                self.tableKhoa.insertRow(row_num)
                for col_num, col_data in enumerate(row_data):
                     self.tableKhoa.setItem(row_num, col_num, QtWidgets.QTableWidgetItem(str(col_data)))

    def retranslateUi(self, QuanLyKhoa):
        _translate = QtCore.QCoreApplication.translate
        QuanLyKhoa.setWindowTitle(_translate("QuanLyKhoa", "Quản Lý Khoa"))
        self.label.setText(_translate("QuanLyKhoa", "QUẢN LÝ KHOA"))
        self.groupBox.setTitle(_translate("QuanLyKhoa", "Thông Tin Chi Tiết"))
        self.label_2.setText(_translate("QuanLyKhoa", "Mã Khoa:"))
        self.label_3.setText(_translate("QuanLyKhoa", "Tên Khoa:"))
        self.btnEdit.setText(_translate("QuanLyKhoa", "Sửa"))
        self.btnDelete.setText(_translate("QuanLyKhoa", "Xóa"))
        self.groupBox_2.setTitle(_translate("QuanLyKhoa", "Thêm Khoa"))
        self.label_4.setText(_translate("QuanLyKhoa", "Mã Khoa:"))
        self.label_5.setText(_translate("QuanLyKhoa", "Tên Khoa:"))
        self.btnSave.setText(_translate("QuanLyKhoa", "Lưu"))
        self.btnCancel.setText(_translate("QuanLyKhoa", "Hủy"))
        self.label_6.setText(_translate("QuanLyKhoa", "Chức Năng"))
        self.btnSort.setText(_translate("QuanLyKhoa", "Sắp Xếp"))
        self.btnReload.setText(_translate("QuanLyKhoa", "Cập Nhật"))
        self.btnHome.setText(_translate("QuanLyKhoa", "Home"))
        item = self.tableKhoa.horizontalHeaderItem(0)
        item.setText(_translate("QuanLyKhoa", "Mã khoa"))
        item = self.tableKhoa.horizontalHeaderItem(1)
        item.setText(_translate("QuanLyKhoa", "Tên khoa"))

def closeWindow():
    global myDB
    myDB.disconnect()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    app.setQuitOnLastWindowClosed(False)
    app.lastWindowClosed.connect(closeWindow)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_QuanLyKhoa()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())