# Form implementation generated from reading ui file 'QuanLyNienKhoa.ui'
#
# Created by: PyQt6 UI code generator 6.5.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from functools import partial
from database import *

myDB = MY_DB()

class Ui_MainWindow(object):
    global myDB
    def setupUi(self, MainWindow):
        myDB.connect()

        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(664, 594)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 40, 171, 16))
        self.label.setStyleSheet("font: 700 12pt \"Segoe UI\";")
        self.label.setObjectName("label")
        self.groupBox_2 = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox_2.setGeometry(QtCore.QRect(430, 70, 221, 151))
        self.groupBox_2.setStyleSheet("background-color: rgb(255, 240, 166);\n"
"font: 10pt \"Segoe UI\";")
        self.groupBox_2.setObjectName("groupBox_2")
        self.label_5 = QtWidgets.QLabel(parent=self.groupBox_2)
        self.label_5.setGeometry(QtCore.QRect(10, 30, 101, 16))
        self.label_5.setStyleSheet("font: 10pt \"Segoe UI\";")
        self.label_5.setObjectName("label_5")
        self.NameNienKhoa = QtWidgets.QLineEdit(parent=self.groupBox_2)
        self.NameNienKhoa.setGeometry(QtCore.QRect(10, 60, 161, 22))
        self.NameNienKhoa.setStyleSheet("font: 10pt \"Segoe UI\";")
        self.NameNienKhoa.setReadOnly(False)
        self.NameNienKhoa.setObjectName("NameNienKhoa")
        self.btnSave = QtWidgets.QPushButton(parent=self.groupBox_2)
        self.btnSave.setGeometry(QtCore.QRect(60, 110, 61, 24))
        self.btnSave.setStyleSheet("background-color: rgb(0, 255, 127);")
        self.btnSave.setObjectName("btnSave")
        self.btnCancel = QtWidgets.QPushButton(parent=self.groupBox_2)
        self.btnCancel.setGeometry(QtCore.QRect(140, 110, 61, 24))
        self.btnCancel.setStyleSheet("background-color: rgb(170, 170, 127);")
        self.btnCancel.setObjectName("btnCancel")
        self.err = QtWidgets.QLabel(parent=self.groupBox_2)
        self.err.setGeometry(QtCore.QRect(10, 90, 161, 16))
        self.err.setStyleSheet("color: rgb(170, 0, 0);\n"
"font: 9pt \"Segoe UI\";")
        self.err.setText("")
        self.err.setObjectName("err")
        self.label_6 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(430, 40, 131, 21))
        self.label_6.setStyleSheet("font: 700 12pt \"Segoe UI\";")
        self.label_6.setObjectName("label_6")
        self.groupBox = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(430, 230, 221, 131))
        self.groupBox.setStyleSheet("background-color: rgb(112, 200, 255);\n"
"font: 10pt \"Segoe UI\";")
        self.groupBox.setObjectName("groupBox")
        self.detailNameNienKhoa = QtWidgets.QLineEdit(parent=self.groupBox)
        self.detailNameNienKhoa.setGeometry(QtCore.QRect(100, 60, 101, 22))
        self.detailNameNienKhoa.setStyleSheet("font: 10pt \"Segoe UI\";")
        self.detailNameNienKhoa.setReadOnly(True)
        self.detailNameNienKhoa.setObjectName("detailNameNienKhoa")
        self.btnDelete = QtWidgets.QPushButton(parent=self.groupBox)
        self.btnDelete.setGeometry(QtCore.QRect(140, 90, 61, 24))
        self.btnDelete.setStyleSheet("background-color: rgb(170, 0, 0);\n"
"color: rgb(255, 255, 255);")
        self.btnDelete.setObjectName("btnDelete")
        self.label_7 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_7.setGeometry(QtCore.QRect(10, 60, 91, 16))
        self.label_7.setStyleSheet("font: 10pt \"Segoe UI\";")
        self.label_7.setObjectName("label_7")
        self.label_9 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_9.setGeometry(QtCore.QRect(10, 30, 101, 16))
        self.label_9.setStyleSheet("font: 10pt \"Segoe UI\";")
        self.label_9.setObjectName("label_9")
        self.detailIDNienKhoa = QtWidgets.QLineEdit(parent=self.groupBox)
        self.detailIDNienKhoa.setGeometry(QtCore.QRect(100, 30, 101, 22))
        self.detailIDNienKhoa.setStyleSheet("font: 10pt \"Segoe UI\";")
        self.detailIDNienKhoa.setReadOnly(True)
        self.detailIDNienKhoa.setObjectName("detailIDNienKhoa")
        self.btnHome = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnHome.setGeometry(QtCore.QRect(10, 0, 71, 31))
        self.btnHome.setStyleSheet("font: 10pt \"Segoe UI\";\n"
"background-color: rgb(255, 255, 127);")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("images/ic/icHome.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btnHome.setIcon(icon)
        self.btnHome.setIconSize(QtCore.QSize(20, 20))
        self.btnHome.setObjectName("btnHome")
        self.tableNienKhoa = QtWidgets.QTableWidget(parent=self.centralwidget)
        self.tableNienKhoa.setGeometry(QtCore.QRect(10, 60, 411, 491))
        self.tableNienKhoa.setRowCount(5)
        self.tableNienKhoa.setColumnCount(2)
        self.tableNienKhoa.setColumnWidth(0, 150)
        self.tableNienKhoa.setColumnWidth(1, 261)
        self.tableNienKhoa.setObjectName("tableNienKhoa")
        item = QtWidgets.QTableWidgetItem()
        self.tableNienKhoa.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableNienKhoa.setHorizontalHeaderItem(1, item)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 664, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.btnHome.clicked.connect(partial(self.goHome, MainWindow))

        self.nienKhoaTable = myDB.select_all_nienkhoa()

        self.tableNienKhoa.setRowCount(0)
        for row_num, row_data in enumerate(self.nienKhoaTable):
                self.tableNienKhoa.insertRow(row_num)
                for col_num, col_data in enumerate(row_data):
                     self.tableNienKhoa.setItem(row_num, col_num, QtWidgets.QTableWidgetItem(str(col_data)))
        
        self.tableNienKhoa.cellClicked.connect(self.on_tableNienKhoa_cellClicked)

        self.btnSave.clicked.connect(self.on_btnSave_clicked)
        self.btnCancel.clicked.connect(self.cancel)

        self.btnDelete.clicked.connect(self.delete)

    def goHome(self, MainWindow):
        from MainWindow import Ui_MainWindow as Ui_MainWindow
        self.window = QtWidgets.QMainWindow()
        self.ui = Ui_MainWindow()
        self.ui.setupUi(self.window)
        MainWindow.close()
        self.window.show()

#-----------------------------INSERT--------------------------------------------
    # def get_NienKhoa_info(self):
    #     tenNienKhoa = self.NameNienKhoa.text()
    #     return tenNienKhoa

    def on_btnSave_clicked(self):
        tenNienKhoa = self.NameNienKhoa.text().strip()

        if tenNienKhoa == "":
            self.err.setText("Không bỏ trống dữ liệu !!")
            return
        # Thêm niên khóa vào CSDL
        myDB.insert_nienkhoa(tenNienKhoa)
        self.cancel()
        # # Thông báo thành công
        # QtWidgets.QMessageBox.information(self, "Thông báo", f"Thêm khoa {makhoa} thành công.")
        self.load_data()

    def cancel(self):
        self.NameNienKhoa.setText("")
        self.err.setText("")

    def on_tableNienKhoa_cellClicked(self, row, column):
        # Lấy mã khoa từ dòng được click
        manienKhoa = self.tableNienKhoa.item(row, 0).text()

        # Lấy thông tin nienKhoa từ CSDL
        nienKhoa = myDB.select_nienkhoa_by_id(manienKhoa).fetchone()

        # Hiển thị thông tin nienKhoa trong groupBox
        self.detailIDNienKhoa.setText(str(nienKhoa[0]))
        self.detailNameNienKhoa.setText(nienKhoa[1])
#-----------------------------------DELETE----------------------------------------------------
    def delete(self):
        current_id = self.detailIDNienKhoa.text()
        if current_id == "":
             return self.load_data()
        else:
             myDB.delete_nienkhoa(current_id)
             self.detailIDNienKhoa.setText("")
             self.detailNameNienKhoa.setText("")
             self.load_data()

    def load_data(self):
        self.err.setText("")
        self.nienKhoaTable = myDB.select_all_nienkhoa()
        self.tableNienKhoa.setRowCount(0)
        for row_num, row_data in enumerate(self.nienKhoaTable):
                self.tableNienKhoa.insertRow(row_num)
                for col_num, col_data in enumerate(row_data):
                     self.tableNienKhoa.setItem(row_num, col_num, QtWidgets.QTableWidgetItem(str(col_data)))

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Quản Lý Niên Khóa"))
        self.label.setText(_translate("MainWindow", "QUẢN LÝ NIÊN KHÓA"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Thêm Niên Khóa"))
        self.label_5.setText(_translate("MainWindow", "Tên Niên Khóa: "))
        self.btnSave.setText(_translate("MainWindow", "Lưu"))
        self.btnCancel.setText(_translate("MainWindow", "Hủy"))
        self.label_6.setText(_translate("MainWindow", "Chức Năng"))
        self.groupBox.setTitle(_translate("MainWindow", "Thông Tin Chi Tiết"))
        self.btnDelete.setText(_translate("MainWindow", "Xóa"))
        self.label_7.setText(_translate("MainWindow", "Tên Niên Khóa: "))
        self.label_9.setText(_translate("MainWindow", "Mã Niên Khóa"))
        self.btnHome.setText(_translate("MainWindow", "Home"))
        item = self.tableNienKhoa.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Mã niên khóa"))
        item = self.tableNienKhoa.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Tên niên khóa"))

def closeWindow():
    global myDB
    myDB.disconnect()
    
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    app.setQuitOnLastWindowClosed(False)
    app.lastWindowClosed.connect(closeWindow)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
